### ISSUE TITLE
Error while installing requirements in venv

### ISSUE THREAD

**Issue by ahthserhsluk** [deshwalmahesh/NSE-Stock-Scanner#5]
Hey I tried multiple times to install with different venv too, but this error seems not to go away. can anyone help?

```
Collecting cffi==1.14.6 (from -r .\requirements.txt (line 14))
  Using cached cffi-1.14.6.tar.gz (475 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ahths\AppData\Local\Temp\pip-install-gw0wbfc3\cffi_7f4ee61a58a94fea84319a7a624fe815\setup.py", line 127, in <module>     
          if sys.platform == 'win32' and uses_msvc():
                                         ^^^^^^^^^^^
        File "C:\Users\ahths\AppData\Local\Temp\pip-install-gw0wbfc3\cffi_7f4ee61a58a94fea84319a7a624fe815\setup.py", line 105, in uses_msvc    
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\projects\2. nse\env\Lib\site-packages\setuptools\_distutils\command\config.py", line 224, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "E:\projects\2. nse\env\Lib\site-packages\setuptools\_distutils\command\config.py", line 129, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)       
        File "E:\projects\2. nse\env\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
        File "E:\projects\2. nse\env\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\projects\2. nse\env\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ahthserhsluk** [comment]
**Update**


Had a similar problem during installations of pandas, scipy, pyzmq, pyYAML, cffi

The solution that worked for me: installing them individually and installing from the requirement.txt

**Comment by deshwalmahesh** [comment]
@ahthserhsluk did you use the exactly same Python version for the venv? There might be some conflicts.
